-- ==========================================
-- CyberGuard AI : Supabase Schema Definition
-- Enterprise RAI & Multi-Agent Architecture
-- Safe & Idempotent (Runs cleanly on existing or fresh DB)
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Enable the pgvector extension for RAG embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ==========================================
-- CORE TABLES
-- ==========================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'Employee',
    readiness_score INTEGER DEFAULT 50,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure all columns exist if table was previously created
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'Employee';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS readiness_score INTEGER DEFAULT 50;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Automatic Auth.users -> Public.users Sync Trigger (Google OAuth / Email Signups)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, role, readiness_score)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'role', 'Employee'),
    50
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.users.full_name);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution on auth.users insert
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. SCENARIOS TABLE (Generated by Scenario Agent)
CREATE TABLE IF NOT EXISTS public.scenarios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    difficulty TEXT NOT NULL,
    target_role TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. DECISIONS TABLE (Evaluated by Evaluation Agent)
CREATE TABLE IF NOT EXISTS public.decisions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    scenario_id UUID REFERENCES public.scenarios(id) ON DELETE CASCADE,
    chosen_action TEXT NOT NULL,
    reasoning TEXT NOT NULL,
    evaluation JSONB,
    is_safe BOOLEAN,
    human_review_required BOOLEAN DEFAULT false, -- RAI: Flagged if Evaluation Agent has low confidence
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- KNOWLEDGE BASE TABLES (RAG / pgvector)
-- ==========================================

-- 4. ORG KNOWLEDGE TABLE (Owner: Scenario Agent)
CREATE TABLE IF NOT EXISTS public.org_knowledge (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores source document name, department, page numbers
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. CYBER THREATS TABLE (Owner: Evaluation Agent)
CREATE TABLE IF NOT EXISTS public.cyber_threats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    source TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores FBI/NCSC URL, date published for citations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. CYBER TRAINING TABLE (Owner: Coach Agent)
CREATE TABLE IF NOT EXISTS public.cyber_training (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    channel TEXT DEFAULT 'email', -- e.g., 'email', 'slack_teams', 'voice_phone', 'qr_code', 'cloud_oauth', 'sms_push', 'physical_media'
    target_risk_surface TEXT DEFAULT 'general', -- e.g., 'financial_access', 'privileged_access', 'pii_phi', 'source_code', 'executive'
    source TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores NIST/SANS framework citations, cognitive biases
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.cyber_training ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'email';
ALTER TABLE public.cyber_training ADD COLUMN IF NOT EXISTS target_risk_surface TEXT DEFAULT 'general';

-- ==========================================
-- AGENT STATE & AUDIT LOGS
-- ==========================================

-- 7. USER LEARNING PROFILE (Owner: Coach Agent)
CREATE TABLE IF NOT EXISTS public.user_learning_profile (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    next_difficulty TEXT DEFAULT 'beginner',
    next_focus TEXT,
    avoid_type TEXT,
    tactic_to_target TEXT,
    target_channel TEXT DEFAULT 'email', -- Multi-channel vector target
    primary_attack_surface TEXT, -- AI-decomposed risk profile
    training_map JSONB, -- Personalized defense sectors created by Coach Agent
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.user_learning_profile ADD COLUMN IF NOT EXISTS target_channel TEXT DEFAULT 'email';
ALTER TABLE public.user_learning_profile ADD COLUMN IF NOT EXISTS primary_attack_surface TEXT;
ALTER TABLE public.user_learning_profile ADD COLUMN IF NOT EXISTS training_map JSONB;

-- 8. AGENT AUDIT LOGS (RAI Traceability)
CREATE TABLE IF NOT EXISTS public.agent_audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_name TEXT NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    model_version TEXT, -- RAI: Tracks exact LLM version (e.g., gpt-4o-mini-2024-07-18)
    prompt_version TEXT, -- RAI: Tracks version of system prompt used
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on ALL tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_knowledge ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyber_threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyber_training ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_learning_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_audit_logs ENABLE ROW LEVEL SECURITY;

-- 1. Scenarios: Read-only for authenticated users
DROP POLICY IF EXISTS "Scenarios are viewable by everyone" ON public.scenarios;
CREATE POLICY "Scenarios are viewable by everyone" ON public.scenarios FOR SELECT USING (true);

-- 2. Decisions: Users can only read/insert their own decisions
DROP POLICY IF EXISTS "Users can view their own decisions" ON public.decisions;
DROP POLICY IF EXISTS "Users can insert their own decisions" ON public.decisions;
CREATE POLICY "Users can view their own decisions" ON public.decisions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own decisions" ON public.decisions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. User Learning Profile: Users can READ their own profile (Coach Agent uses service_role to update)
DROP POLICY IF EXISTS "Users can view their own learning profile" ON public.user_learning_profile;
CREATE POLICY "Users can view their own learning profile" ON public.user_learning_profile FOR SELECT USING (auth.uid() = user_id);

-- 4. Users table: Users can view their own record
DROP POLICY IF EXISTS "Users can view own profile" ON public.users;
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);

-- 5. RAG Tables & Audit Logs: 
-- NO POLICIES DEFINED FOR REGULAR USERS. 
-- Only backend FastAPI services (using service_role key) can read/write directly.
