-- ==========================================
-- CyberGuard AI : Supabase Schema Definition
-- Enterprise RAI & Multi-Agent Architecture
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Enable the pgvector extension for RAG embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ==========================================
-- CORE TABLES
-- ==========================================

-- 1. USERS TABLE
CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL,
    readiness_score INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SCENARIOS TABLE (Generated by Scenario Agent)
CREATE TABLE public.scenarios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    difficulty TEXT NOT NULL,
    target_role TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. DECISIONS TABLE (Evaluated by Evaluation Agent)
CREATE TABLE public.decisions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    scenario_id UUID REFERENCES public.scenarios(id) ON DELETE CASCADE,
    chosen_action TEXT NOT NULL,
    reasoning TEXT NOT NULL,
    evaluation JSONB,
    is_safe BOOLEAN,
    human_review_required BOOLEAN DEFAULT false, -- RAI: Flagged if Evaluation Agent has low confidence
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- KNOWLEDGE BASE TABLES (RAG / pgvector)
-- ==========================================

-- 4. ORG KNOWLEDGE TABLE (Owner: Scenario Agent)
CREATE TABLE public.org_knowledge (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores source document name, department, page numbers
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. CYBER THREATS TABLE (Owner: Evaluation Agent)
CREATE TABLE public.cyber_threats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    source TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores FBI/NCSC URL, date published for citations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. CYBER TRAINING TABLE (Owner: Coach Agent)
CREATE TABLE public.cyber_training (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category TEXT NOT NULL,
    source TEXT NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    metadata JSONB, -- RAI: Stores NIST/SANS framework citations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- AGENT STATE & AUDIT LOGS
-- ==========================================

-- 7. USER LEARNING PROFILE (Owner: Coach Agent)
CREATE TABLE public.user_learning_profile (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    next_difficulty TEXT DEFAULT 'beginner',
    next_focus TEXT,
    avoid_type TEXT,
    tactic_to_target TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. AGENT AUDIT LOGS (RAI Traceability)
CREATE TABLE public.agent_audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_name TEXT NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    model_version TEXT, -- RAI: Tracks exact LLM version (e.g., gpt-4o-mini-2024-07-18)
    prompt_version TEXT, -- RAI: Tracks version of system prompt used
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on ALL tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_knowledge ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyber_threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyber_training ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_learning_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_audit_logs ENABLE ROW LEVEL SECURITY;

-- 1. Scenarios: Read-only for authenticated users
CREATE POLICY "Scenarios are viewable by everyone" ON public.scenarios FOR SELECT USING (true);

-- 2. Decisions: Users can only read/insert their own decisions
CREATE POLICY "Users can view their own decisions" ON public.decisions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own decisions" ON public.decisions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. User Learning Profile: Users can READ their own profile (Coach Agent uses service_role to update)
CREATE POLICY "Users can view their own learning profile" ON public.user_learning_profile FOR SELECT USING (auth.uid() = user_id);

-- 4. RAG Tables & Audit Logs: 
-- NO POLICIES DEFINED FOR USERS. 
-- This completely locks down these tables. Only the backend FastAPI application 
-- (using the Supabase service_role key) can read/write to the knowledge bases and audit logs.
